config/routes.rb
Rails.application.routes.draw do
  require 'admin_constraint'
  mount Ckeditor::Engine => '/ckeditor', constraints: AdminConstraint.new
  root 'home#index'
  resources :profiles
  
  match '/about'              =>        'home#about',              via: [:get],            :as => 'about'
  match '/join-our-team'              =>        'home#join',              via: [:get],            :as => 'join'
  match '/privacy-policy'              =>        'home#privacy_policy',              via: [:get],            :as => 'privacy_policy'
  match "/contacts"              =>        "contacts#create",              via: [:post]
  match "/applicants"            =>        "applicants#create",            via: [:post]

  match '/inflight-catering'              =>        'industries#inflight_catering',              via: [:get],            :as => 'inflight_catering'
  match '/industrial-catering'              =>        'industries#industrial_catering',              via: [:get],            :as => 'industrial_catering'
  match '/concessions'              =>        'industries#concessions',              via: [:get],            :as => 'concessions'
  match '/restaurants'              =>        'industries#restaurants',              via: [:get],            :as => 'restaurants'
  match '/retail'              =>        'industries#retail',              via: [:get],            :as => 'retail'
  match '/oil-gas-mining'              =>        'industries#oil_gas_mining',              via: [:get],            :as => 'oil_gas_mining'
  match '/commercial-airline-catering'              =>        'industries#commercial_airline_catering',              via: [:get],            :as => 'commercial_airline_catering'
  match '/private-inflight-catering'              =>        'industries#private_inflight_catering',              via: [:get],            :as => 'private_inflight_catering'


  devise_scope :user do
    get "/users/sign_up",  :to => "devise/sessions#new"
  end
  
  devise_for :users

  devise_scope :user do 
    get "/admin" => "devise/sessions#new" 
  end

  #########################################
  #==locations url for location model
  #########################################
    # get '/locations', to: 'locations#index', as: :locations
    post 'locations', to: 'locations#create'
    get '/locations/new', to: 'locations#new', as: :new_location
    get 'locations/:title_for_slug/edit', to: 'locations#edit', as: 'edit_location'
    get 'locations/:title_for_slug', to: 'locations#show', as: 'location'
    patch 'locations/:title_for_slug', to: 'locations#update'
    put 'locations/:title_for_slug', to: 'locations#update'
    delete 'locations/:title_for_slug', to: 'locations#destroy'

  #########################################
  #==news url for blog model
  #########################################
    get '/news', to: 'blogs#index', as: :blogs
    post 'news', to: 'blogs#create'
    get '/news/new', to: 'blogs#new', as: :new_blog
    get 'news/:title_for_slug/edit', to: 'blogs#edit', as: 'edit_blog'
    get 'news/:title_for_slug', to: 'blogs#show', as: 'blog'
    patch 'news/:title_for_slug', to: 'blogs#update'
    put 'news/:title_for_slug', to: 'blogs#update'
    delete 'news/:title_for_slug', to: 'blogs#destroy'

    get '/sitemap.xml', to: redirect("https://s3-us-west-2.amazonaws.com/gcg-catering/sitemaps/sitemap.xml.gz", status: 301)

    match "*path", to: "home#catch_all", via: :all
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @blogs = Blog.order(pubdate: "desc").limit(3)
  end

  def about
  end

  def join
  end

  def privacy_policy
  end

  def catch_all
    @blogs = Blog.order(pubdate: "desc").limit(3)
    flash.now[:warning] = "The page or request you were looking for was not found."
    render :index
  end
end

app/views/home/about.html.erb
<% provide(:title, 'Full-Service Catering in the Caribbean and Latin America | GCG Catering') %>
<% content_for :head do%>
  <meta name="description" content="GCG Catering serves our clients with 60 years of experience and more than 3,000 team members spread across 24 locations in the Caribbean & Latin America.">
  <!-- <meta name="keywords" content="about keywords"> -->
  <!-- <link rel="canonical" href="http://www.mysite.com/mypage/"/> -->
<% end %>

<!-- Hero  -->
<section class="hero-about" title="About GCG Caribbean and Latin America catering"></section>

<section class="about">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 text-center">
        <h3 class="mb30">About GCG Catering</h3>
        <p class="mt60">GCG Catering is a leading full-service HACCP compliant catering company with 24 locations across the Caribbean and Latin America. Our team is made up of 3,000 highly-trained employees, who adhere to the highest standards in the industry. We produce 23 million meals per year, servicing more than 75 of the world’s leading airlines and an extensive portfolio of 140 industrial clients. Our team has a longstanding history of meeting and exceeded expectations, while remaining at the leading edge of innovation.</p>
      </div>
    </div>
  </div>
</section>

<!-- Services  -->
<%= render 'industries/other_industries' %>

<!-- Locations  -->
<%= render 'industries/industries_where_we_are' %>

<!-- Contact Us  -->
<%= render 'layouts/second_contact_form' %>

app/views/home/index.html.erb
<% provide(:title, 'Inflight, Industrial, and Restaurant Catering | GCG Catering') %>
<% content_for :head do%>
  <meta name="description" content="GCG Catering is available for a wide range of industries and needs. We provide inflight catering and concessions, industrial, restaurant & retail catering.">
  <!-- <meta name="keywords" content="home keywords"> -->
  <!-- <link rel="canonical" href="http://www.mysite.com/mypage/"/> -->
<% end %>


<!-- Hero  -->
<section class="slide">
	<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
		<!-- Indicators -->
		<ol class="carousel-indicators">
			<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
			<li data-target="#carousel-example-generic" data-slide-to="1"></li>
			<li data-target="#carousel-example-generic" data-slide-to="2"></li>
		</ol>

		<!-- Wrapper for slides -->
		<div class="carousel-inner" role="listbox">
			<div class="item active">
        <div class="hero-home" title="Catered Caribbean and Latin America events by GCG" style="background-image: url('https://s3-us-west-2.amazonaws.com/gcg-catering/hero/hero-home03.jpg');"></div>
			</div>
			<div class="item">
				<div class="hero-home" title="Caribbean and Latin America catering by GCG" style="background-image: url('https://s3-us-west-2.amazonaws.com/gcg-catering/hero/hero-home01.jpg');"></div>
			</div>
			<div class="item">
        <div class="hero-home"  title="Corporate event catering in the Caribbean by GCG" style="background-image: url('https://s3-us-west-2.amazonaws.com/gcg-catering/hero/hero-home02.jpg');"></div>
			</div>
		</div>
	</div>
</section>


<!-- Industries  -->
<section class="bg-light-grey">
	<div class="container">
		<div class="row text-center">
			<h1 class="title-first mb60">Industries We Serve</h1>

			
			<div class="col-md-4 col-xs-6 colMobile">
				<div class="box-services">
					<div class="wrap-img">
						<a href="/inflight-catering">
							<img src="https://s3-us-west-2.amazonaws.com/gcg-catering/industries/industries-inflight-catering.jpg" alt="Inflight Catering by GCG" class="img-responsive center-block"/>
						</a>
					</div>
					<div class="text green">
						<a href="/inflight-catering">
							<div class="icon">
								<img class="img-responsive center-block" src="https://s3-us-west-2.amazonaws.com/gcg-catering/industries/inflight.png" alt="Inflight Catering by GCG">
							</div>
						</a>
						<h4 class="mt15 mb10"><a class="secondary" href="/inflight-catering">Inflight Catering</a></h4>
						<p>Food has always played an important role in providing...</p>
						<a href="/inflight-catering" class="btn btn-custom-secondary-border transition pl20 pr20 mt15">Read more</a>
					</div>
				</div>
			</div>
			<div class="col-md-4 col-xs-6 colMobile">
				<div class="box-services">
					<div class="wrap-img">
						<a href="/industrial-catering">
							<img src="https://s3-us-west-2.amazonaws.com/gcg-catering/industries/industries-industrial.jpg" alt="Industrial Catering by GCG" class="img-responsive center-block"/>
						</a>
					</div>
					<div class="text">
						<a href="/industrial-catering">
							<div class="icon">
								<img class="img-responsive center-block" src="https://s3-us-west-2.amazonaws.com/gcg-catering/industries/industrial.png" alt="Industrial Catering by GCG">
							</div>
						</a>
						<h4 class="mt15 mb10"><a href="/industrial-catering">Industrial Catering</a></h4>
						<p>When it comes to feeding your team, you need a caterer...</p>
						<a href="/industrial-catering" class="btn btn-custom-primary-border transition pl20 pr20 mt15">Read more</a>
					</div>
				</div>
			</div>
			<div class="col-md-4 col-xs-6 colMobile">
				<div class="box-services">
					<div class="wrap-img">
						<a href="/concessions">
							<img src="https://s3-us-west-2.amazonaws.com/gcg-catering/industries/industries-concessions.jpg" alt="Concessions Catering by GCG" class="img-responsive center-block"/>
						</a>
					</div>
					<div class="text green">
						<a href="/concessions">
							<div class="icon">
								<img class="img-responsive center-block" src="https://s3-us-west-2.amazonaws.com/gcg-catering/industries/consesions.png" alt="Concessions Catering by GCG">
							</div>
						</a>	
						<h4 class="mt15 mb10"><a class="secondary" href="/concessions">Concessions</a></h4>
						<p>Traveling can be stressful for passengers, but when...</p>
						<a href="/concessions" class="btn btn-custom-secondary-border transition pl20 pr20 mt15">Read more</a>
					</div>
				</div>
			</div>
			<div class="col-md-4 col-xs-6 colMobile">
				<div class="box-services">
					<div class="wrap-img">
						<a href="/restaurants">
							<img src="https://s3-us-west-2.amazonaws.com/gcg-catering/industries/industries-restaurants.jpg" alt="Restaurant catering by GCG Catering" class="img-responsive center-block"/>
						</a>
					</div>
					<div class="text">
						<a href="/restaurants">
							<div class="icon">
								<img class="img-responsive center-block" src="https://s3-us-west-2.amazonaws.com/gcg-catering/industries/restaurants.png" alt="Restaurant catering by GCG Catering">
							</div>
						</a>
						<h4 class="mt15 mb10"><a href="/restaurants">Restaurants</a></h4>
						<p>When traveling by air, one is likely to spend a great deal...</p>
						<a href="/restaurants" class="btn btn-custom-primary-border transition pl20 pr20 mt15">Read more</a>
					</div>
				</div>
			</div>
			<div class="col-md-4 col-xs-6 colMobile">
				<div class="box-services">
					<div class="wrap-img">
						<a href="/retail">
							<img src="https://s3-us-west-2.amazonaws.com/gcg-catering/industries/industries-retail-catering.jpg" alt="Retail event catering by GCG Catering" class="img-responsive center-block"/>
						</a>
					</div>
					<div class="text green">
						<a href="/retail">
							<div class="icon">
								<img class="img-responsive center-block" src="https://s3-us-west-2.amazonaws.com/gcg-catering/industries/retail.png" alt="Retail event catering by GCG Catering">
							</div>
						</a>
						<h4 class="mt15 mb10"><a class="secondary" href="/retail">Retail Solutions</a></h4>
						<p>Building a menu to suit the needs of a large group can...</p>
						<a href="/retail" class="btn btn-custom-secondary-border transition pl20 pr20 mt15 ">Read more</a>
					</div>
				</div>
			</div>
			<div class="col-md-4 col-xs-6 colMobile">
				<div class="box-services">
					<div class="wrap-img">
						<a href="/oil-gas-mining">
							<img src="https://s3-us-west-2.amazonaws.com/gcg-catering/industries/industries-mining.jpg" alt="Oil,Gas & Mining catering by GCG Catering" class="img-responsive center-block"/>
						</a>
					</div>
					<div class="text">
						<a href="/oil-gas-mining">
							<div class="icon">
								<img class="img-responsive center-block" src="https://s3-us-west-2.amazonaws.com/gcg-catering/industries/oil.png" alt="Oil,Gas & Mining catering by GCG Catering">
							</div>
						</a>
						<h4 class="mt15 mb10"><a href="/oil-gas-mining">Oil, Gas & Mining</a></h4>
						<p>In order to maintain a quality workforce, employers in...</p>
						<a href="/oil-gas-mining" class="btn btn-custom-primary-border transition pl20 pr20 mt15">Read more</a>
						
					</div>
				</div>
			</div>
		</div>
	</div>
</section>


<!-- Location  -->
<section class="bg-light-primary">
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<h3 class="mb60 title-white text-center">Our Locations</h3>
				<div class="maps" id="myid" data-mylocations="<%= @locations.to_json %>">

        <div id="map" style="height:450px;"></div>
      
      </div>


				</div>
			</div>
		</div>
	</div>
</section>

<!-- latest news  -->

<section class="news bg-light-grey">
  <div class="container">
    <div class="row">
      <h4 class="mb30 title-first text-center">Latest News</h4>
      <% @blogs.each do |blog| %>
        <div class="col-sm-4 col-xs-12 mt60 mb30 pull-left">
            <a href="<%= blog_path(blog.title_for_slug) %>"><div class="img-blog"  style="background-image: url(<%= blog.images[-1].pic.url(:large) %>);"></div></a>
          <h5><%= link_to blog.title, blog_path(blog.title_for_slug) %></h5>
          <p><%= HTML_Truncator.truncate(blog.content_index, 15).html_safe %></p>
          <%= link_to 'Read More >', blog_path(blog.title_for_slug), class: "btn" %>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/home/join.html.erb
<% provide(:title, 'Career Opportunities | GCG Catering') %>
<% content_for :head do%>
  <meta name="description" content="Enlisting the best employees is the only way we can ensure client expectations are met and exceeded. Apply to join the GCG Catering team today.">
  <!-- <meta name="keywords" content="home keywords"> -->
  <!-- <link rel="canonical" href="http://www.mysite.com/mypage/"/> -->
<% end %>

<!-- Hero  -->
<section class="hero-join"></section>

<section class="about">
	<div class="container">
		<div class="row">
			<div class="col-sm-12 text-center">
				<h3 class="mb30">Join Our Team</h3>
				<p class="mt60 mb60">Enlisting the best employees is the only way we can ensure client expectations are met and exceeded. We’ve assembled a talented team across our many locations, and we’re always looking for passionate individuals to join it. <br/><br/>We offer a wide variety of opportunities for individuals at all levels of experience to grow within the industry. Complete the form below to learn more about our open positions.</p>
			</div>
			<div class="col-sm-10 col-sm-offset-1">
				<div class="message">

					<%= form_for :applicant, :html => { :id => "new_applicant", class: "join"}, :url => {:controller => "applicants", :action => "create"} do |f| %>
						<div class="col-sm-6 col-sm-offset-3">
					    <div class="form-group">
					      <%= f.label :full_name, class: "sr-only" %>
					      <%= f.text_field :full_name, class: "form-control", placeholder: "Full Name*", required: true %>
					    </div>
					  </div>
						<div class="col-sm-6 col-sm-offset-3">
					    <div class="form-group">
					      <%= f.label :email, class: "sr-only" %>
					      <%= f.email_field :email, class: "form-control", placeholder: "Email*", required: true %>
					    </div>
					  </div>
						<div class="col-sm-6 col-sm-offset-3">
					    <div class="form-group">
					      <%= f.label :phone_number, class: "sr-only" %>
					      <%= f.text_field :phone_number, class: "form-control", placeholder: "Phone*", required: true %>
					    </div>
					  </div>
						<div class="col-sm-6 col-sm-offset-3">
					    <div class="form-group">
					      <%= f.label :location, class: "sr-only" %>
					      <%= f.select :location_id, Location.order(name: :asc).all.map {|u| [u.name, u.id]}, {prompt: "Select Career Location"}, required: true, class: "form-control" %>
					    </div>
					  </div>
						<div class="col-sm-6 col-sm-offset-3">
					    <div class="form-group">
					      <%= f.label :resume, "Resume (pdf only)" %>
					      <%= f.file_field :resume, required: true %>
					    </div>
					  </div>
						<div class="col-sm-6 col-sm-offset-3">
					    <div class="form-group">
					      <%= f.submit "Submit", class: "btn btn-default btn-xl btn-custom-primary" %>
					    </div>
					  </div>
				  <% end %>

				</div>
			</div>
		</div>
	</div>
</section>